name:                basics
version:             0.1.0.0
github:              githubuser/basics
license:             BSD3
author:              Author name here
maintainer:          example@example.com
copyright:           2017 Author name here

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on Github at <https://github.com/githubuser/basics#readme>

dependencies:
- array
- base >= 4.7 && < 5
- bytestring
- containers
- directory
- filepath
- mtl
- parsec
- QuickCheck
- random
- regex-posix >= 0.95.2
- time

library:
  source-dirs:
    - src/
    - src/lyhfgg/
    - src/rwh/examples/
    - src/rwh/json/
    - src/rwh/io/
    - src/rwh/regex/
    - src/rwh/binary-parsing/
    - src/rwh/functors/
    - src/rwh/testing/
    - src/rwh/bar-code/
    - src/rwh/data-structures/
    - src/rwh/monads/
    - src/rwh/parsec

executables:
  basics-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - basics

tests:
  basics-test:
    main:                BasicsTest.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - basics
