name:                learn-servant
version:             0.1.0.0
github:              "githubuser/learn-servant"
license:             BSD3
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2017 Author name here"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on Github at <https://github.com/githubuser/learn-servant#readme>

dependencies:
- aeson
- attoparsec
- base >= 4.7 && < 5
- base-compat
- blaze-html
- blaze-markup
- bytestring
- directory
- http-media
- mtl
- servant
- servant-server
- string-conversions
- text
- time
- wai
- warp

library:
  source-dirs: src

executables:
  learn-servant-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - learn-servant

tests:
  learn-servant-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - learn-servant
